baseurl: '/'
permalink: pretty
title: 'Hippo Ventures'

logo:
  mobile: "images/logo/hippo-ventures-logo-mobile.png"
  mobile_height: "32px"
  mobile_width: "120px"
  desktop: "images/logo/hippo-ventures-logo.png"
  desktop_height: "128px"
  desktop_width: "480px"

home: 
  limit_portfoliocompanies: 6

collections:
  portfoliocompanies:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "portfoliocompanies"
    values:
      layout: "portfoliocompany"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
